# Generated by Django 4.1.1 on 2022-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('documento', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=30)),
            ],
        ),
    ]
