# Generated by Django 4.1.1 on 2022-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
