# Generated by Django 4.1.1 on 2022-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_clientes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Genero', models.CharField(max_length=30)),
                ('Añosalida', models.IntegerField()),
                ('Tipojuego', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Usuario',
        ),
    ]
