# Generated by Django 4.1.1 on 2022-11-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_juego_rename_clientes_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='Añosalida',
            new_name='aniosalida',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='Genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='Tipojuego',
            new_name='tipojuego',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
