# Generated by Django 4.1.1 on 2022-11-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_añosalida_juego_aniosalida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
