# Generated by Django 4.1.1 on 2022-11-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_juego_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='aniosalida',
            new_name='año_de_salida',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='tipojuego',
            new_name='tipo_de_juego',
        ),
    ]
