# Generated by Django 4.1.1 on 2022-11-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
